# Generated by Django 4.0.4 on 2022-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256, verbose_name='Раздел')),
                ('main', models.BooleanField(verbose_name='Основной')),
                ('articles', models.ManyToManyField(related_name='relationships', to='articles.article')),
            ],
        ),
    ]
