# Generated by Django 4.0.4 on 2022-05-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_relationship_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Подкрепить к разделу', 'verbose_name_plural': 'Подкрепить к разделу'},
        ),
        migrations.AlterField(
            model_name='relationship',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_main', to='articles.article', verbose_name='Выбрать статью'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_main', to='articles.tags', verbose_name='Выбрать раздел'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(related_name='tags', through='articles.Relationship', to='articles.article'),
        ),
    ]
