# Generated by Django 4.0.4 on 2022-05-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_relationship_articles_alter_relationship_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='relationship',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='articles.article', verbose_name='Выбрать статью'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='articles.tags', verbose_name='Выбрать раздел'),
        ),
    ]
