# Generated by Django 4.0.4 on 2022-05-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_teacher_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.student')),
                ('name_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.teacher')),
            ],
        ),
    ]
